### ISSUE TITLE
Compatibility with FPS dynamic shadows - Shadow Boost

### ISSUE THREAD

**Issue by SpookiePoogie** [rhoot/fo4-wrench#5]
Hi I wonder if there is a way you can make this mod compatible with the FPS dynamic shadows. It adjust the shadows setting dynamically based on frame rate but the problem is that it uses the xinput1_3.dll to implement its features as well. Maybe there is a way you two can combine a .dll as a fix.
here is a link to the mod: http://www.nexusmods.com/fallout4/mods/1822/?

**Comment by SpookiePoogie** [comment]
Apparently renaming one of the xinput1_3.dll to x360ce.dll fixes the problem!

**Comment by rhoot** [comment]
This is actually one of the reasons you can specify in the config where it should load the "real" XInput DLL from. I know a lot of people play with [x360ce](https://github.com/x360ce/x360ce), and wanted to support that.

Seems you found an alternative solution though. Glad it worked out. I'll close this for now, and if someone else has issues with it in the future they can reopen it.
